version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inferencias_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
